### ISSUE TITLE
swagger.json or Open API?

### ISSUE THREAD

**Issue by frankhommers** [transip/tipctl#1]
This might not be the right place to ask this, but it's certainly close to the fire.

Do you also have a swagger.json (or open api 3 file) of your API? That way I can easily create it for other other platforms.

**Comment by stefankonig** [comment]
Hi Frank,

Thank you for your suggestion, we have added links to both APIB and OpenAPI specifications for the Rest API on our documentation page https://api.transip.nl/rest/docs.html

happy coding :)
