### ISSUE TITLE
Please upgrade the code to support PHP 8

### ISSUE THREAD

**Issue by MarcelRothuizen** [transip/tipctl#5]
# tipctl.phar --version

Box Requirements Checker
========================

> Using PHP 8.0.2
> PHP is using the following php.ini file:
  /etc/php.ini

> Checking Box requirements:
  E....

 [ERROR] Your system is not ready to run the application.

Fix the following mandatory requirements:
=========================================

 * The application requires the version "^7.2.0" or greater.

**Comment by samihsoylu** [comment]
Hi Marcel,

Thanks for your input. 

Tipctl now supports PHP 8.0+ please download the release v6.6.1

Happy coding!

Samih.
